version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  web:
    build: ./web
    ports: 
      - 5000:5000
    volumes:
      - './web:/usr/src/app'
    depends_on: 
      - db
    environment:
      - CORS=1
      - CONFIG=main.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
    command:  ["gunicorn", "--bind", "0.0.0.0:5000", "--reload", "--worker-class", "eventlet", "-w", "1", "manage:app"]
    # command: python manage.py
  
  client:
    build: ./client
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - './client/src:/usr/src/app/src'
    command: npm start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - web
      - client
    ports:
      - 80:80