version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
    
  redis:
    image: redis
    
  web:
    build: ./web
    ports: 
      - 8080:8080
    depends_on: 
      - db
      - redis
    environment:
      - CONFIG=main.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
  
  client:
    build: ./client
    volumes:
      - static:/usr/src/app/build

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static:/usr/src/app
    depends_on:
      - web
      - client

volumes:
  static: