version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back
    
  web:
    build: ./web
    ports: 
      - 8080:8080
    depends_on: 
      - db
    environment:
      - NODE_ENV=prod
      - CONFIG=main.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
      - SECRET=hidememore
    networks:
      - back
  
  client:
    build: ./client
    volumes:
      - static:/usr/src/app/build

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/usr/src/app
      - ./dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/circlechat.cc/fullchain.pem:/etc/letsencrypt/live/circlechat.cc/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/circlechat.cc/privkey.pem:/etc/letsencrypt/live/circlechat.cc/privkey.pem

    depends_on:
      - web
      - client
    networks:
      - front
      - back

volumes:
  static:
  db-data:

networks:
  front:
  back: