version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - back
  
  redis:
    image: redis
    volumes:
      - ./data:/data
    networks:
      - back
    
  web:
    build: ./web
    ports: 
      - '8080'
    volumes:
      - './web/app:/src/app'
    depends_on: 
      - db
      - redis
    environment:
      - NODE_ENV=dev
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
    command: ["npm", "run", "dev"]
    networks:
        - back
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - './client/src:/usr/src/app/src'
    command: npm start
    networks:
        - front
        - back

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - web
      - client
    ports:
      - 80:80
    networks:
      - front
      - back

volumes:
  static:
  db-data:

networks:
  front:
  back: