version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  
  redis:
    image: redis
    volumes:
      - ./data:/data
    
  web:
    build: ./web
    ports: 
      - 8080:8080
    volumes:
      - './web/app:/src/app'
    depends_on: 
      - db
      - redis
    environment:
      - CONFIG=main.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
    command: ["npm", "run", "dev"]
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    depends_on:
      - web
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3000:3000
    volumes:
      - './client/src:/usr/src/app/src'
    command: npm start

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - web
      - client
    ports:
      - 80:80