version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
  
  web:
    build: ./web
    ports: 
      - 8080:8080
    depends_on: 
      - db
    environment:
      - CONFIG=main.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    # volumes:
    #   - static:/somewhere

  client:
    build: ./client
    depends_on:
      - web
      - nginx
    # volumes:
    #   - static:usr/src/build
    
  # frontend:
  #   build: ./frontend
  #   ports:
  #     - 80:80