version: "3"
services:
  db:
    build: ./db
    ports: 
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    #volumes:
  web:
    build: ./web
    ports: 
      - 8080:8080
    volumes:
      - './web:/usr/src/app'
    depends_on: 
      - db
    environment:
      - CONFIG=main.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@db:5432/test
  frontend:
    build: ./frontend
    ports:
      - 80:80
    